export enum GameEffectSetStateType {
  CONFUSED = 1,
  FRIGHTENED = 2,
  DROID_STUN = 3,
  CUT_SCENE_STUNNED = 4,
  CUT_SCENE_PARALYZE = 5,
  SLEEP = 6,
  CHOKE = 7,
  CUT_SCENE_HORRIFIED = 8,
  FORCEPUSH = 9,
  WHIRLWIND = 10,
}