/**
 * GameEffectType enum.
 *
 * KotOR JS - A remake of the Odyssey Game Engine that powered KotOR I & II
 *
 * @file GameEffectType.ts
 * @author KobaltBlu <https://github.com/KobaltBlu>
 * @license {@link https://www.gnu.org/licenses/gpl-3.0.txt|GPLv3}
 * @enum
 */
export enum GameEffectType {
  EffectHaste = 0x01,
  EffectDamageResistance = 0x02,
  EffectSlow = 0x03,
  EffectResurrection = 0x04,
  EffectDisease = 0x05,
  EffectSummonCreature = 0x06,
  EffectRegenerate = 0x07,
  EffectSetState = 0x08,
  EffectSetStateInternal = 0x09,
  EffectAttackIncrease = 0x0a,
  EffectAttackDecrease = 0x0b,
  EffectDamageReduction = 0x0c,
  EffectDamageIncrease = 0x0d,
  EffectDamageDecrease = 0x0e,
  EffectTemporaryHitPoints = 0x0f,
  EffectDamageImmunityIncrease = 0x10,
  EffectDamageImmunityDecrease = 0x11,
  EffectEntangle = 0x12,
  EffectDeath = 0x13,
  EffectKnockdown = 0x14,
  EffectDeaf = 0x15,
  EffectImmunity = 0x16,
  EffectSetAIState = 0x17,
  EffectEnemyAttackBonus = 0x18,
  EffectArcaneSpellFailure = 0x19,
  EffectSavingThrowIncrease = 0x1a,
  EffectSavingThrowDecrease = 0x1b,
  EffectMovementSpeedIncrease = 0x1c,
  EffectMovementSpeedDecrease = 0x1d,
  EffectVisualEffect = 0x1e,
  EffectAreaOfEffect = 0x1f,
  EffectBeam = 0x20,
  EffectForceResistanceIncrease = 0x21,
  EffectForceResistanceDecrease = 0x22,
  EffectPoison = 0x23,
  EffectAbilityIncrease = 0x24,
  EffectAbilityDecrease = 0x25,
  EffectDamage = 0x26,
  EffectHeal = 0x27,
  EffectLink = 0x28,
  EffectModifyNumAttacks = 0x2c,
  EffectCurse = 0x2d,
  EffectSilence = 0x2e,
  EffectInvisibility = 0x2f,
  EffectACIncrease = 0x30,
  EffectACDecrease = 0x31,
  EffectSpellImmunity = 0x32,
  EffectDispellMagic = 0x33,
  EffectDispellMagicBest = 0x34,
  EffectLight = 0x36,
  EffectSkillIncrease = 0x37,
  EffectSkillDecrease = 0x38,
  EffectHitPointChangeWhenDying = 0x39,
  EffectSetWalkAnimation = 0x3a,
  EffectLimitMovementSpeed = 0x3b,
  EffectForcePushed = 0x3c,
  EffectDamageShield = 0x3d,
  EffectDisguise = 0x3e,
  EffectSanctuary = 0x3f,
  EffectTimeStop = 0x40,
  EffectSpellLevelAbsorption = 0x41,
  EffectIcon = 0x43,
  EffectRacialType = 0x44,
  EffectSeeInvisible = 0x46,
  EffectUltraVision = 0x47,
  EffectTrueseeing = 0x48,
  EffectBlindness = 0x49,
  EffectDarkness = 0x4a,
  EffectMissChance = 0x4b,
  EffectConcealment = 0x4c,
  EffectAppear = 0x51,
  EffectNegativeLevel = 0x52,
  EffectBonusFeat = 0x53,
  EffectSummonParty = 0x59,
  EffectForceDrain = 0x5a,
  EffectTemporaryForce = 0x5b,
  EffectBlasterDeflectionIncrease = 0x5c,
  EffectBlasterDeflectionDecrease = 0x5d,
  EffectDamageForcePoints = 0x5f,
  EffectHealForcePoints = 0x60,
  EffectBodyFuel = 0x62,
  EffectPsychicStatic = 0x63,
  EffectLightSaberThrow = 0x64,
  EffectAssuredHit = 0x65,
  EffectForceJump = 0x66,
  EffectAssuredDeflection = 0x68,
  EffectForceResisted = 0x69,
  EffectForceFizzle = 0x6a,
  EffectForceShield = 0x6b,
  EffectPureGoodPowers = 0x6c,
  EfffectPureEvilPowers = 0x6d,
  EffectInvalidEffect,
}
