/**
 * 
 */
export enum EngineDebugType {
  CONTROLS = 'CONTROLS',
  SELECTED_OBJECT = 'SELECTED_OBJECT',
  OBJECT_LABELS = 'OBJECT_LABELS',
  PATH_FINDING = 'PATH_FINDING',

  /**
   * Walkmesh
   */
  ROOM_WALKMESH = 'ROOM_WALKMESH',
  DOOR_WALKMESH = 'DOOR_WALKMESH',
  PLACEABLE_WALKMESH = 'PLACEABLE_WALKMESH',
}